"""Write the four organize-it-yourself deliverables plus the picking sheet."""
import argparse
import csv
import os
import shlex
import stat
import sys

from tools import classify, dupes, eventdata, naming, scan

GB = 1024.0 ** 3


def write_events_manifest(events, analysis, conflicts, path, global_dupes=None):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    lines = []
    lines.append("# Event manifest\n")
    lines.append("Tick the events you want in the portfolio gallery, then run")
    lines.append("`python3 -m tools.hydrate --events <id> <id> ...`\n")
    # `events` includes one record per catch-all mirror folder too (it needs
    # those to compute per-folder photo/byte counts), so the unique-event
    # count June actually cares about is the non-catchall subset.
    unique_events = [e for e in events if not e["catchall"]]
    unique_empty = [e for e in unique_events if e["photos"] == 0]
    lines.append("- %d unique events (%d with photos, %d empty folders)"
                 % (len(unique_events), len(unique_events) - len(unique_empty),
                    len(unique_empty)))
    lines.append("- cleanup.sh can safely move %d files (%.2f GB) -- duplicates "
                 "inside catch-all folders, matched to a sibling event folder"
                 % (analysis["removable_files"], analysis["removable_bytes"] / GB))
    if global_dupes is not None:
        outside = global_dupes["files"] - analysis["removable_files"]
        outside_bytes = (global_dupes["bytes"] - analysis["removable_bytes"]) / GB
        lines.append(
            "- the archive's *total* name+size duplication is larger: %d files "
            "(%.2f GB). The extra %d files (%.2f GB) are duplicates that live "
            "**outside** catch-all folders -- picking which copy to keep needs "
            "a person, so cleanup.sh does not touch them. **cleanup.sh only "
            "reclaims the %.2f GB figure above, not this one.**"
            % (global_dupes["files"], global_dupes["bytes"] / GB,
               outside, outside_bytes, analysis["removable_bytes"] / GB))
    lines.append("")

    if conflicts:
        lines.append("## Needs your decision\n")
        lines.append("The archive gives one event two different dates:\n")
        for c in conflicts:
            lines.append("- **%s** — %s" % (c["title"], " vs ".join(c["dates"])))
            for p in c["paths"]:
                lines.append("  - `%s`" % p)
        lines.append("")

    empties = [e for e in events if e["photos"] == 0 and not e["catchall"]]
    if empties:
        lines.append("## Empty folders\n")
        lines.append("%d event folders exist but hold no photos:\n" % len(empties))
        for e in empties:
            lines.append("- `%s`" % e["dir"])
        lines.append("")

    by_category = {}
    for e in events:
        if e["catchall"]:
            continue
        by_category.setdefault(e["category"], []).append(e)

    for cid in classify.CATEGORIES:
        group = by_category.get(cid)
        if not group:
            continue
        note = "  ← not recommended for publication" if cid == "internal" else ""
        lines.append("## %s (%d events)%s\n" % (classify.LABELS[cid], len(group), note))
        if cid == "other":
            lines.append(
                "> Caution: this catch-all bucket can include internal/staff-facing "
                "events that just don't match the other keyword rules (for example, "
                "insurance-enrollment events like \"Anthem BCBS Health Care AEEP In "
                "Roll\" or \"UHC 2026 AEP Rollout Dinner - Flushing\"). Check each "
                "row here before publishing, the same way you would for "
                "Internal / Provider.\n")
        lines.append("| pick | date | event | photos | physician | partners | id |")
        lines.append("|---|---|---|---|---|---|---|")
        for e in group:
            lines.append("| [ ] | %s | %s | %d | %s | %s | `%s` |" % (
                e["iso"] or (str(e["year_num"]) if e["year_num"] else "?"),
                e["title"].replace("|", "/"),
                e["photos"],
                e["physician"] or "",
                ", ".join(e["partners"]),
                e["id"],
            ))
        lines.append("")

    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def write_rename_plan(events, path):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["current_path", "current_name", "proposed_name",
                         "photos", "category"])
        for e in events:
            writer.writerow([e["dir"], e["event"], e["proposed"],
                             e["photos"], e["category"]])
    return len(events)


_HEADER = """#!/usr/bin/env bash
# Generated by tools/manifests.py on {stamp}. Review before running.
#
# Moves duplicate files into the quarantine folder below. Nothing is
# deleted. Re-run {undo_name} to reverse every move.
#
#   bash {script_name}            # dry run, prints what would move
#   bash {script_name} --apply    # actually move
#
# Quarantine: {quarantine_dir}
#
# After checking the quarantine folder, delete it from the OneDrive web UI,
# which keeps a 93-day recycle bin.
set -euo pipefail

APPLY=0
[[ "${{1:-}}" == "--apply" ]] && APPLY=1
if [[ $APPLY -eq 0 ]]; then
  echo "DRY RUN -- nothing will move. Re-run with --apply to act."
fi

"""

_UNDO_HEADER = """#!/usr/bin/env bash
# Generated by tools/manifests.py on {stamp}. Reverses {script_name}.
#
#   bash {undo_name}            # dry run, prints what would restore
#   bash {undo_name} --apply    # actually restore
set -euo pipefail

APPLY=0
[[ "${{1:-}}" == "--apply" ]] && APPLY=1
if [[ $APPLY -eq 0 ]]; then
  echo "DRY RUN -- nothing will move. Re-run with --apply to act."
fi

"""

_FOOTER = """
if [[ $APPLY -eq 1 ]]; then
  echo "Moved {count} files into {quarantine_dir}"
  echo "Reverse with: bash {undo_name} --apply"
else
  echo "{count} files would move. Re-run with --apply."
fi
"""

_UNDO_FOOTER = """
if [[ $APPLY -eq 1 ]]; then
  echo "Restored {count} files from {quarantine_dir}"
else
  echo "{count} files would be restored. Re-run with --apply."
fi
"""


def _removable(analysis):
    rels = []
    for entry in analysis["full"]:
        rels.extend(r["rel"] for r in entry["rows"])
    for entry in analysis["partial"]:
        rels.extend(r["rel"] for r in entry["dup_rows"])
    return sorted(set(rels))


def _chmod_x(path):
    st = os.stat(path)
    os.chmod(path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _move_block(src_abs, dst_abs, rel, verb):
    """One self-contained, fully-quoted guarded move.

    Every path is resolved to an absolute path and quoted with shlex.quote
    at generation time -- there is no shell-variable path-building to get
    wrong, and real folder names in this archive contain spaces, '&', '#',
    parentheses and apostrophes.
    """
    src_q = shlex.quote(src_abs)
    dst_q = shlex.quote(dst_abs)
    dstdir_q = shlex.quote(os.path.dirname(dst_abs))
    rel_q = shlex.quote(rel)
    return (
        "if [[ -e %s ]]; then\n"
        "  if [[ $APPLY -eq 1 ]]; then\n"
        "    mkdir -p %s\n"
        "    mv %s %s\n"
        "  else\n"
        "    printf '%%s %%s\\n' %s %s\n"
        "  fi\n"
        "else\n"
        "  printf 'skip (already gone): %%s\\n' %s\n"
        "fi\n"
    ) % (src_q, dstdir_q, src_q, dst_q,
         shlex.quote("would %s:" % verb), rel_q, rel_q)


def write_cleanup(analysis, archive_root, path, undo_path, stamp):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    rels = _removable(analysis)
    quarantine_name = "_DUPLICATES_%s" % stamp
    archive_abs = os.path.abspath(archive_root)
    quarantine_abs = os.path.join(archive_abs, quarantine_name)
    script_name = os.path.basename(path)
    undo_name = os.path.basename(undo_path)

    with open(path, "w") as fh:
        fh.write(_HEADER.format(stamp=stamp, script_name=script_name,
                                undo_name=undo_name,
                                quarantine_dir=quarantine_abs))
        for rel in rels:
            src_abs = os.path.join(archive_abs, rel)
            dst_abs = os.path.join(quarantine_abs, rel)
            fh.write(_move_block(src_abs, dst_abs, rel, "move"))
        fh.write(_FOOTER.format(count=len(rels), quarantine_dir=quarantine_abs,
                                undo_name=undo_name))
    _chmod_x(path)

    with open(undo_path, "w") as fh:
        fh.write(_UNDO_HEADER.format(stamp=stamp, script_name=script_name,
                                     undo_name=undo_name))
        for rel in rels:
            src_abs = os.path.join(archive_abs, rel)      # original location
            dst_abs = os.path.join(quarantine_abs, rel)    # quarantined location
            fh.write(_move_block(dst_abs, src_abs, rel, "restore"))
        fh.write(_UNDO_FOOTER.format(count=len(rels), quarantine_dir=quarantine_abs))
    _chmod_x(undo_path)
    return len(rels)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Write archive manifests (read-only).")
    ap.add_argument("--archive", required=True)
    ap.add_argument("--out", default="tools/out")
    ap.add_argument("--stamp", default="2026-10-05")
    args = ap.parse_args(argv)

    out = args.out
    inv_stats = scan.write_inventory(args.archive, os.path.join(out, "inventory.csv"))
    rows = list(scan.walk(args.archive))
    analysis = dupes.analyze(rows)
    global_dupes = dupes.global_redundancy(rows)
    dupes.write_csv(analysis, os.path.join(out, "duplicates.csv"))
    events = eventdata.collect_events(
        rows, extra_dirs=eventdata.find_empty_event_dirs(args.archive))
    conflicts = naming.find_conflicts([
        {"name": e["event"], "iso": e["iso"], "path": e["dir"]}
        for e in events if not e["catchall"]
    ])
    write_events_manifest(events, analysis, conflicts,
                          os.path.join(out, "events-manifest.md"),
                          global_dupes=global_dupes)
    write_rename_plan(events, os.path.join(out, "rename-plan.csv"))
    moves = write_cleanup(analysis, args.archive,
                          os.path.join(out, "cleanup.sh"),
                          os.path.join(out, "undo.sh"), args.stamp)

    empties = len([e for e in events if e["photos"] == 0])
    print("files        %d (%.1f GB)" % (inv_stats["files"], inv_stats["bytes"] / GB))
    print("downloaded   %.1f%%" % (100.0 * inv_stats["hydrated"] / max(inv_stats["files"], 1)))
    print("events       %d (%d empty folders)"
          % (len([e for e in events if not e["catchall"]]), empties))
    print("duplicates   scriptable: %d files, %.2f GB  |  global: %d files, %.2f GB"
          % (analysis["removable_files"], analysis["removable_bytes"] / GB,
             global_dupes["files"], global_dupes["bytes"] / GB))
    print("conflicts    %d" % len(conflicts))
    print("cleanup.sh   %d moves queued (dry run by default)" % moves)
    print("\nwrote %s/{inventory.csv,duplicates.csv,events-manifest.md,"
          "rename-plan.csv,cleanup.sh,undo.sh}" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
